# Generated by Django 4.2.6 on 2023-10-14 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_contactprofile_options_alter_skill_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='skills',
        ),
        migrations.AlterModelTable(
            name='skill',
            table='main_skill',
        ),
    ]
